# Generated by Django 2.0.3 on 2018-03-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('S', 'Started'), ('C', 'Continued'), ('F', 'Finished')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='original_unix_time',
            field=models.IntegerField(default=0),
        ),
    ]
