# Generated by Django 2.0.3 on 2018-03-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20180325_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.Entry'),
        ),
        migrations.AddField(
            model_name='mediaevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.Entry'),
        ),
    ]
