# Generated by Django 2.0.3 on 2018-03-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20180325_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fname',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
